version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=nest_next_template
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 15432:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  